DELETE FROM categoria CASCADE;
DELETE FROM categoria_simples CASCADE;
DELETE FROM super_categoria CASCADE;
DELETE FROM constituida CASCADE;
DELETE FROM produto CASCADE;
DELETE FROM fornecedor CASCADE;
DELETE FROM fornece_sec CASCADE;
DELETE FROM planograma CASCADE;
DELETE FROM prateleira CASCADE;
DELETE FROM corredor CASCADE;
DELETE FROM evento_reposicao CASCADE;
DELETE FROM reposicao CASCADE;
DROP TRIGGER check_categoria_type_sup ON super_categoria CASCADE;
DROP TRIGGER check_categoria_type_simp ON categoria_simples CASCADE;
DROP TRIGGER categoria_verify ON constituida CASCADE;
DROP TRIGGER date_verify ON evento_reposicao CASCADE;
DROP TRIGGER fornece_sec_verify ON fornece_sec CASCADE;
DROP FUNCTION check_categoria_type_sup() CASCADE;
DROP FUNCTION check_categoria_type_simp() CASCADE;
DROP FUNCTION categoria_verify() CASCADE;
DROP FUNCTION date_verify() CASCADE;
DROP FUNCTION fornece_sec_verify() CASCADE;
DROP TABLE reposicao CASCADE;
DROP TABLE planograma CASCADE;
DROP TABLE evento_reposicao CASCADE;
DROP TABLE categoria_simples CASCADE;
DROP TABLE constituida CASCADE;
DROP TABLE fornece_sec CASCADE;
DROP TABLE prateleira CASCADE;
DROP TABLE corredor CASCADE;
DROP TABLE super_categoria CASCADE;
DROP TABLE produto CASCADE;
DROP TABLE categoria CASCADE;
DROP TABLE fornecedor CASCADE;